name: CI
on:
  merge_group: {}
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: 📦 Install dependencies
        run: pnpm ii
        shell: bash
      - name: 🧹 Run lint
        run: pnpm lint

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: 📦 Install dependencies
        run: pnpm ii
        shell: bash
      - name: 📦 Opt out of image optimization
        run: "sed -i 's/unoptimized: false/unoptimized: true/' next.config.js"
        shell: bash
      - name: 📦 sanity check
        run: |
          wc -c <<<"${PAYLOAD_SECRET}"
          cksum --algorithm md5 <<<"${PAYLOAD_SECRET}"
        shell: bash
        env:
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      - name: 🧹 Run build
        run: pnpm build
        shell: bash
        env:
          DATABASE_URI: 'file:./dev.db.seeded'
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: 📦 Install dependencies
        run: pnpm ii
        shell: bash
      - name: 🧹 Run prettier
        run: if ! pnpm prettier --check .; then echo "⚠️  Run 'pnpm prettify' to fix prettier errors & commit the result"; exit 1; fi
