name: cleanup
on:
  delete:
    branches-ignore:
      - 'main'
      - 'preview'
      - 'release'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Install Turso CLI
        run: curl -sSfL https://get.tur.so/install.sh | bash
      - name: Delete preview database
        run: |
          ref="${{ github.ref_name }}"
          name="payloadcms-preview-${name//[^a-z0-9\-]/x}"
          turso db destroy --yes "${name}"
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
# TODO: clean up Vercel deployment?
